// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package bookmarks

import (
	"sync"
)

// Ensure, that URLCheckerMock does implement URLChecker.
// If this is not the case, regenerate this file with moq.
var _ URLChecker = &URLCheckerMock{}

// URLCheckerMock is a mock implementation of URLChecker.
//
//	func TestSomethingThatUsesURLChecker(t *testing.T) {
//
//		// make and configure a mocked URLChecker
//		mockedURLChecker := &URLCheckerMock{
//			CheckFunc: func(url string, originalTitle string) (string, int64, int64, string) {
//				panic("mock out the Check method")
//			},
//		}
//
//		// use mockedURLChecker in code that requires URLChecker
//		// and then make assertions.
//
//	}
type URLCheckerMock struct {
	// CheckFunc mocks the Check method.
	CheckFunc func(url string, originalTitle string) (string, int64, int64, string)

	// calls tracks calls to the methods.
	calls struct {
		// Check holds details about calls to the Check method.
		Check []struct {
			// URL is the url argument value.
			URL string
			// OriginalTitle is the originalTitle argument value.
			OriginalTitle string
		}
	}
	lockCheck sync.RWMutex
}

// Check calls CheckFunc.
func (mock *URLCheckerMock) Check(url string, originalTitle string) (string, int64, int64, string) {
	if mock.CheckFunc == nil {
		panic("URLCheckerMock.CheckFunc: method is nil but URLChecker.Check was just called")
	}
	callInfo := struct {
		URL           string
		OriginalTitle string
	}{
		URL:           url,
		OriginalTitle: originalTitle,
	}
	mock.lockCheck.Lock()
	mock.calls.Check = append(mock.calls.Check, callInfo)
	mock.lockCheck.Unlock()
	return mock.CheckFunc(url, originalTitle)
}

// CheckCalls gets all the calls that were made to Check.
// Check the length with:
//
//	len(mockedURLChecker.CheckCalls())
func (mock *URLCheckerMock) CheckCalls() []struct {
	URL           string
	OriginalTitle string
} {
	var calls []struct {
		URL           string
		OriginalTitle string
	}
	mock.lockCheck.RLock()
	calls = mock.calls.Check
	mock.lockCheck.RUnlock()
	return calls
}
