// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package web

import (
	"cirello.io/alreadyread/pkg/bookmarks"
	"sync"
)

// Ensure, that URLCheckerMock does implement bookmarks.URLChecker.
// If this is not the case, regenerate this file with moq.
var _ bookmarks.URLChecker = &URLCheckerMock{}

// URLCheckerMock is a mock implementation of bookmarks.URLChecker.
//
//	func TestSomethingThatUsesURLChecker(t *testing.T) {
//
//		// make and configure a mocked bookmarks.URLChecker
//		mockedURLChecker := &URLCheckerMock{
//			CheckFunc: func(url string, originalTitle string) (string, int64, int64, string) {
//				panic("mock out the Check method")
//			},
//			TitleFunc: func(url string) string {
//				panic("mock out the Title method")
//			},
//		}
//
//		// use mockedURLChecker in code that requires bookmarks.URLChecker
//		// and then make assertions.
//
//	}
type URLCheckerMock struct {
	// CheckFunc mocks the Check method.
	CheckFunc func(url string, originalTitle string) (string, int64, int64, string)

	// TitleFunc mocks the Title method.
	TitleFunc func(url string) string

	// calls tracks calls to the methods.
	calls struct {
		// Check holds details about calls to the Check method.
		Check []struct {
			// URL is the url argument value.
			URL string
			// OriginalTitle is the originalTitle argument value.
			OriginalTitle string
		}
		// Title holds details about calls to the Title method.
		Title []struct {
			// URL is the url argument value.
			URL string
		}
	}
	lockCheck sync.RWMutex
	lockTitle sync.RWMutex
}

// Check calls CheckFunc.
func (mock *URLCheckerMock) Check(url string, originalTitle string) (string, int64, int64, string) {
	if mock.CheckFunc == nil {
		panic("URLCheckerMock.CheckFunc: method is nil but URLChecker.Check was just called")
	}
	callInfo := struct {
		URL           string
		OriginalTitle string
	}{
		URL:           url,
		OriginalTitle: originalTitle,
	}
	mock.lockCheck.Lock()
	mock.calls.Check = append(mock.calls.Check, callInfo)
	mock.lockCheck.Unlock()
	return mock.CheckFunc(url, originalTitle)
}

// CheckCalls gets all the calls that were made to Check.
// Check the length with:
//
//	len(mockedURLChecker.CheckCalls())
func (mock *URLCheckerMock) CheckCalls() []struct {
	URL           string
	OriginalTitle string
} {
	var calls []struct {
		URL           string
		OriginalTitle string
	}
	mock.lockCheck.RLock()
	calls = mock.calls.Check
	mock.lockCheck.RUnlock()
	return calls
}

// Title calls TitleFunc.
func (mock *URLCheckerMock) Title(url string) string {
	if mock.TitleFunc == nil {
		panic("URLCheckerMock.TitleFunc: method is nil but URLChecker.Title was just called")
	}
	callInfo := struct {
		URL string
	}{
		URL: url,
	}
	mock.lockTitle.Lock()
	mock.calls.Title = append(mock.calls.Title, callInfo)
	mock.lockTitle.Unlock()
	return mock.TitleFunc(url)
}

// TitleCalls gets all the calls that were made to Title.
// Check the length with:
//
//	len(mockedURLChecker.TitleCalls())
func (mock *URLCheckerMock) TitleCalls() []struct {
	URL string
} {
	var calls []struct {
		URL string
	}
	mock.lockTitle.RLock()
	calls = mock.calls.Title
	mock.lockTitle.RUnlock()
	return calls
}
