name: Go

on:
  push:
    branches: [ main ]
  merge_group:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: golangci-lint cache
      uses: actions/cache@v4
      with:
        path: ~/go/bin/golangci-lint
        key: ${{ runner.os }}-golangci-lint

    - name: Test
      run: |
        make linters test

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage.html
