name: Go

on:
  push:
    branches: [ master ]
  pull_request:
  merge_group:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: golangci-lint cache
      uses: actions/cache@v3
      with:
        path: ~/go/bin/golangci-lint
        key: ${{ runner.os }}-golangci-lint-v1.54.2

    - name: Test
      run: |
        make linters test

    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.html
