name: TryBot

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [labeled]

permissions:
  contents: read
  pull-requests: read
  issues: write      # to add/remove the label

concurrency:
  group: trybot-${{ github.event_name == 'pull_request_target' && github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: true

jobs:
  run_ci:
    if: github.event_name == 'pull_request_target' &&
        contains(join(github.event.pull_request.labels.*.name), 'trybot')
    uses: ./.github/workflows/go.yml
