name: TryBot

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [edited]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: trybot-${{ github.event_name == 'pull_request_target' && github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: true

jobs:
  comment_listener:
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    steps:
      - id: gate
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.comment.body || '';
            const allowed = ['MEMBER','OWNER','COLLABORATOR']
              .includes(context.payload.comment.author_association);
            const ok = /trybot\+1/i.test(body) && allowed;
            core.setOutput('ok', ok ? 'true' : 'false');

      - name: Append trybot ping to PR body (no PAT, no labels)
        if: steps.gate.outputs.ok == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.issue.number;
            const { data: pr } = await github.rest.pulls.get({ owner, repo, pull_number: prNumber });
            const prev = pr.body || '';
            const stamp = Date.now();
            const ping  = `<!-- trybot-ping:${stamp} -->`;
            const next  = prev + "\n" + ping;
            await github.rest.pulls.update({ owner, repo, pull_number: prNumber, body: next });
            core.info(`Added ${ping}`);

  run_ci:
    if: >
      github.event_name == 'pull_request_target' &&
      github.event.action == 'edited' &&
      github.event.changes.body != null &&
      contains(github.event.pull_request.body, '<!-- trybot-ping:') &&
      !contains(github.event.changes.body.from, '<!-- trybot-ping:')
    uses: ./.github/workflows/go.yml
